### ISSUE TITLE
Move project into actix-extras

### ISSUE THREAD

**Issue by chris-ricketts** [Chris-Ricketts/actix-broker#14]
As I am no longer actively developing `actix-broker` it was [suggested](https://github.com/chris-ricketts/actix-broker/pull/13#issuecomment-722479646) by @robjtede that it be moved to the official `actix-extras` repo.

@robjtede what can I do to help?

**Comment by robjtede** [comment]
thoughts on this @JohnTitor ?

**Comment by JohnTitor** [comment]
If @chris-ricketts wants, we're happy to maintain `actix-broker` on `actix-extras` repo!

**Comment by robjtede** [comment]
Alright @chris-ricketts so you can submit a PR to the extras repo and archive this. We'll link to it for history lookups.

**Comment by JohnTitor** [comment]
And could you add @robjtede or me to the crate owners on crates.io?

**Comment by chris-ricketts** [comment]
@robjtede @JohnTitor done and done. 

I sent @robjtede the owner invite - I can send another to @JohnTitor if you want?

I'll wait for everything to be approved before closing and archiving.

**Comment by robjtede** [comment]
I've added acitx/core to the owners list so we're good on that front.

**Comment by robjtede** [comment]
Migration is done. This issue can be closed.
