### ISSUE TITLE
Please add 'actix' topic

### ISSUE THREAD

**Issue by naturallymitchell** [chris-ricketts/actix-broker#8]

**Comment by chris-ricketts** [comment]
Could you give some more info on what you mean? 
The `keywords` property in the `Cargo.toml` already contains 'actix'.

**Comment by naturallymitchell** [comment]
On main project page, see 'Manage Topics', under the project description.  (This is a GitHub feature.)

It adds it to https://github.com/topics/actix

**Comment by chris-ricketts** [comment]
Added - thanks.
